language: python

php:
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.7 WP_MULTISITE=0
    - WP_VERSION=3.7 WP_MULTISITE=1

before_script:
    - phpenv install php-5.6.0
    - bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: echo "Testing!"
